In [6]:
from google.colab import drive
import numpy as np
import pandas as pd

df=pd.read_csv("/content/Airbnb NYC 2019.csv")
print(df)

print(df.head())

print(df.info())

print(df.describe())

print(df['room_type'].value_counts())

print(df['room_type']('price'))

             id                                               name   host_id  \
0          2539                 Clean & quiet apt home by the park      2787
1          2595                              Skylit Midtown Castle      2845
2          3647                THE VILLAGE OF HARLEM....NEW YORK !      4632
3          3831                    Cozy Entire Floor of Brownstone      4869
4          5022   Entire Apt: Spacious Studio/Loft by central park      7192
...         ...                                                ...       ...
48890  36484665    Charming one bedroom - newly renovated rowhouse   8232441
48891  36485057      Affordable room in Bushwick/East Williamsburg   6570630
48892  36485431            Sunny Studio at Historical Neighborhood  23492952
48893  36485609               43rd St. Time Square-cozy single bed  30985759
48894  36487245  Trendy duplex in the very heart of Hell's Kitchen  68119814

           host_name neighbourhood_group       neighbourhood  latitude  \
0               John            Brooklyn          Kensington  40.64749
1           Jennifer           Manhattan             Midtown  40.75362
2          Elisabeth           Manhattan              Harlem  40.80902
3        LisaRoxanne            Brooklyn        Clinton Hill  40.68514
4              Laura           Manhattan         East Harlem  40.79851
...              ...                 ...                 ...       ...
48890        Sabrina            Brooklyn  Bedford-Stuyvesant  40.67853
48891        Marisol            Brooklyn            Bushwick  40.70184
48892  Ilgar & Aysel           Manhattan              Harlem  40.81475
48893            Taz           Manhattan      Hell's Kitchen  40.75751
48894     Christophe           Manhattan      Hell's Kitchen  40.76404

       longitude        room_type  price  minimum_nights  number_of_reviews  \
0      -73.97237     Private room    149               1                  9
1      -73.98377  Entire home/apt    225               1                 45
2      -73.94190     Private room    150               3                  0
3      -73.95976  Entire home/apt     89               1                270
4      -73.94399  Entire home/apt     80              10                  9
...          ...              ...    ...             ...                ...
48890  -73.94995     Private room     70               2                  0
48891  -73.93317     Private room     40               4                  0
48892  -73.94867  Entire home/apt    115              10                  0
48893  -73.99112      Shared room     55               1                  0
48894  -73.98933     Private room     90               7                  0

      last_review  reviews_per_month  calculated_host_listings_count  \
0      2018-10-19               0.21                               6
1      2019-05-21               0.38                               2
2             NaN                NaN                               1
3      2019-07-05               4.64                               1
4      2018-11-19               0.10                               1
...           ...                ...                             ...
48890         NaN                NaN                               2
48891         NaN                NaN                               2
48892         NaN                NaN                               1
48893         NaN                NaN                               6
48894         NaN                NaN                               1

       availability_365
0                   365
1                   355
2                   365
3                   194
4                     0
...                 ...
48890                 9
48891                36
48892                27
48893                 2
48894                23

[48895 rows x 16 columns]
     id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787
1  2595                             Skylit Midtown Castle     2845
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632
3  3831                   Cozy Entire Floor of Brownstone     4869
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976
4        Laura           Manhattan   East Harlem  40.79851  -73.94399

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19
1  Entire home/apt    225               1                 45  2019-05-21
2     Private room    150               3                  0         NaN
3  Entire home/apt     89               1                270  2019-07-05
4  Entire home/apt     80              10                  9  2018-11-19

   reviews_per_month  calculated_host_listings_count  availability_365
0               0.21                               6               365
1               0.38                               2               355
2                NaN                               1               365
3               4.64                               1               194
4               0.10                               1                 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB
None
                 id       host_id      latitude     longitude         price  \
count  4.889500e+04  4.889500e+04  48895.000000  48895.000000  48895.000000
mean   1.901714e+07  6.762001e+07     40.728949    -73.952170    152.720687
std    1.098311e+07  7.861097e+07      0.054530      0.046157    240.154170
min    2.539000e+03  2.438000e+03     40.499790    -74.244420      0.000000
25%    9.471945e+06  7.822033e+06     40.690100    -73.983070     69.000000
50%    1.967728e+07  3.079382e+07     40.723070    -73.955680    106.000000
75%    2.915218e+07  1.074344e+08     40.763115    -73.936275    175.000000
max    3.648724e+07  2.743213e+08     40.913060    -73.712990  10000.000000

       minimum_nights  number_of_reviews  reviews_per_month  \
count    48895.000000       48895.000000       38843.000000
mean         7.029962          23.274466           1.373221
std         20.510550          44.550582           1.680442
min          1.000000           0.000000           0.010000
25%          1.000000           1.000000           0.190000
50%          3.000000           5.000000           0.720000
75%          5.000000          24.000000           2.020000
max       1250.000000         629.000000          58.500000

       calculated_host_listings_count  availability_365
count                    48895.000000      48895.000000
mean                         7.143982        112.781327
std                         32.952519        131.622289
min                          1.000000          0.000000
25%                          1.000000          0.000000
50%                          1.000000         45.000000
75%                          2.000000        227.000000
max                        327.000000        365.000000
Entire home/apt    25409
Private room       22326
Shared room         1160
Name: room_type, dtype: int64